### ISSUE TITLE
Using jupyter-sphinx as a ReST preprocessor without Sphinx

### ISSUE THREAD

**Issue by grothesque** [jupyter/jupyter-sphinx#100]
It seems to me that jupyter-sphinx can be seen as a ReST preprocessor that would be perfectly useful independently of Sphinx.  For example people could use ReST source files with jupyter-execute directives for a blog.

There would be also advantages of using jupyter-sphinx as a ReST preprocessor *with* Sphinx.  The potentially time-consuming execution step would be under the control of a makefile and could be parallelized and controlled independently from Sphinx' limited parallelization and modification detection.  A solution to https://github.com/jupyter/jupyter-sphinx/issues/99 would be also possible quite easily.

Perhaps there is a way to keep jupyter-sphinx the way it is for convenience and backwards compatibility, but factor out the jupyter-execute machinery to optionally make it usable separately?

**Comment by akhmerov** [comment]
Conceptually we do the following:

1. get the AST from sphinx/docutils
2. call nbconvert (which we might want to replace with a more specialized https://github.com/jupyter/nbclient), extract the output.
3. modify the AST.

It seems that only step 2 would be reusable if we wanted to sidestep sphinx, and we'd need to implement quite a bit of analogous machinery on our own.

**Comment by akhmerov** [comment]
Reviewing this again, I believe this is outside of the project scope: we are also reusing for instance sphinx utilities for saving images, defining configuration, and many other things.

Bits and pieces of the codebase are definitely reusable in implementing what you propose, but I don't see an easy and low effort way to keep useful integration with sphinx, while additionally implementing jupyter-sphinx as a sphinx-agnostic rst preprocessor.
