### ISSUE TITLE
Consider factoring out execute.py into sub-modules

### ISSUE THREAD

**Issue by choldgraf** [jupyter/jupyter-sphinx#102]
Looking through execute.py, it seems that there is a lot of different kinds of stuff going on in there that might be easier to manage (at least mentally) if it were separated out a bit.

Something like:

* `execute.py` handles the execution stuff. Things like JupyterKernel nodes etc.
* `utils.py` that has contains the "utilities" section
* `ast.py` that has the `cell_output_to_nodes` logic as well as a collection of generic docutils node objects
* `thebelab.py` has all the thebelab-specific stuff
* move the `setup(app)` function into `__init__.py`

None of this should change the heart of what `jupyter_sphinx` does, but it would help split up that 1000-line python module into more manageable parts. Also, putting `setup(app)` into `__init__.py` would stop sphinx from giving my a warning that it isn't sure `jupyter_sphinx` is a Sphinx extension :-P

What do folks think?

**Comment by akhmerov** [comment]
:+1: on all suggestions!

**Comment by seanpue** [comment]
I would also like the code to use Black. :) I think more abstraction would make domain-specific formatting extension plugins possible, which would be cool.

**Comment by choldgraf** [comment]
I'm all for `Black` personally :-)

If folks are generally +1 on this I can try to do a pure-refactor PR (only cosmetic + structural, no user-facing changes)

**Comment by akhmerov** [comment]
@choldgraf I'd be extremely thankful if you give a go at it. I'm also OK with black. I find it a nuisance in mathy code, but otherwise it's quite decent.

**Comment by akhmerov** [comment]
Closed via #103
