### ISSUE TITLE
Consider a hide-cell option

### ISSUE THREAD

**Issue by choldgraf** [jupyter/jupyter-sphinx#104]
In a recent thread, the following question came up:

*Is it possible to test documentation made with jupyter-sphinx?*

I realized that an easy way to do this would be to insert `jupyter-execute` cells that ran assert statements and typical testing stuff. However, in that case you wouldn't want the actual code to show up in the final docs. Since there is a `hide-input` and `hide-output` option, what about a `hide-cell` option? Alternatively, if both `hide-input` and `hide-output` are given, this could trigger the behavior that *nothing* makes it into the Sphinx AST (and forgive me if this is already what happens!)

**Comment by akhmerov** [comment]
What kind of testing do you have in mind?

`hide-input` does inject the input into the AST to be shown again if thebelab is activated.

I didn't find a good use case for `hide-output` yet—it could even be that it made it into the library for historical compatibility considerations.

**Comment by choldgraf** [comment]
In this case, it's for a series of lecture notes that are hosted with Sphinx. They want to make sure not only that the lectures can run properly, but also do some checks on the values of variables and other outputs.

For hide-output, I agree - the main usecase I know of is to use it with something like `sphinx-togglebutton` in order to make the outputs clickable to show

**Comment by akhmerov** [comment]
Hmm, so would a cell with `hide-input` and no output satisfy these needs? It would have a drawback of showing up in thebelab, but that's still 90% there.

**Comment by choldgraf** [comment]
I think it could work - maybe simply suggesting it as a potential use of the extension rather than changing the codebase?

**Comment by akhmerov** [comment]
Indeed, I am leaning towards adding a remark in the documentation.

**Comment by akhmerov** [comment]
And we can always extend this if there's more demand.

**Comment by choldgraf** [comment]
Makes sense to me - I am a big fan of documenting first, and then only adding new tech if enough people ask for it
