### ISSUE TITLE
Release new PyPi version

### ISSUE THREAD

**Issue by chrisjsewell** [jupyter/jupyter-sphinx#106]
Hey @akhmerov could you release a new version, so that I can use it to release MyST-NB thanks 😄

**Comment by akhmerov** [comment]
You need this because of #103, right?

**Comment by chrisjsewell** [comment]
Yep 👍  and the rest of the commits that @choldgraf has made

**Comment by akhmerov** [comment]
What do you mean? #103 is the only change on this side IIRC.

I'm wondering if the release is better to time with the changes to the AST structure, and incorporating the `CellOutputNote` logic like done in ebp. (CC @choldgraf)

**Comment by chrisjsewell** [comment]
> What do you mean? #103 is the only change on this side IIRC.
> 
> I'm wondering if the release is better to time with the changes to the AST structure, and incorporating the `CellOutputNote` logic like done in ebp. (CC @choldgraf)

In this first instance, the purpose here is purely to generate a baseline MyST-NB version that people can install/use for testing and feedback (rather than just downloading from master). Just an alpha pre-release would be fine.

**Comment by choldgraf** [comment]
Agreed that we want to make some more changes (like the AST stuff) but I'm +1 on a minor release to trigger a chain of other releases haha

**Comment by akhmerov** [comment]
I've made https://pypi.org/project/jupyter-sphinx/0.2.4a1/ does this work for you?

**Comment by chrisjsewell** [comment]
> I've made https://pypi.org/project/jupyter-sphinx/0.2.4a1/ does this work for you?

👌 thanks

**Comment by chrisjsewell** [comment]
FYI, you probably already know, but you can get Travis to auto-deploy to PyPi when you create a new release; as I do in Myst-Parser: https://github.com/ExecutableBookProject/MyST-Parser/blob/40b4de4bdfd76b79a16e8b8a15f613dd85238176/.travis.yml#L41

**Comment by akhmerov** [comment]
I do, but I didn't get around to set it up properly. Since I manage unrelated projects, it'd be prudent to not use the same account for all uploads. Plus I am on the fence wrt storing keys on third party infrastructure.

I'm going to close the issue as addressed. Feel free to reopen if you need something.

**Comment by choldgraf** [comment]
Many thanks @akhmerov! I'll try and return the favor by making some PRs in the coming days 😊
