### ISSUE TITLE
Set up pypi auto-publish with github actions

### ISSUE THREAD

**Issue by choldgraf** [jupyter/jupyter-sphinx#116]
We've got GitHub actions building and publishing new versions in the Executable Books stack, and I think it does a great job of lowering the pain associated with cutting a new release. How do folks feel about this?

If people are +1, then if somebody gives me PyPI access to jupyter-sphinx, I can add a secret that will let us do this!

**Comment by akhmerov** [comment]
I'm :100: on this, @choldgraf what's your pypi account?

**Comment by akhmerov** [comment]
Ah, but I'm not the repo manager; @SylvainCorlay can you add @choldgraf to jupyter-sphinx?

**Comment by choldgraf** [comment]
on PyPI I am @choldgraf as well!

**Comment by SylvainCorlay** [comment]
I added @choldgraf to PyPI!

**Comment by choldgraf** [comment]
it works! https://pypi.org/project/jupyter-sphinx/#history
