### ISSUE TITLE
Add an inline function for cell_outputs_to_nodes

### ISSUE THREAD

**Issue by choldgraf** [jupyter/jupyter-sphinx#123]
In MyST-NB we had to write another version of `cell_outputs_to_nodes` to handle inline use-cases: https://github.com/executablebooks/MyST-NB/blob/d72ebe707d9ca307b4479c07e3eeed0deba6b996/myst_nb/transform.py#L68

we should port that over here and re-use as much of the code as possible from the function in jupyter-sphinx

The only differences that I could find were in the kinds of outputs nodes:

* `literal_block` becomes `literal`: https://github.com/executablebooks/MyST-NB/blob/d72ebe707d9ca307b4479c07e3eeed0deba6b996/myst_nb/transform.py#L106
* `container` objects aren't used in the output nodes: https://github.com/executablebooks/MyST-NB/blob/d72ebe707d9ca307b4479c07e3eeed0deba6b996/myst_nb/transform.py#L105

that might be it - but basically it's just making sure the output nodes are single-line-friendly if there's an `inline` flag.

@chrisjsewell to your knowledge what is the difference between the inline one and the one in here? Is it the kinds of nodes that are output? And if so, maybe we just need an "inline=True" flag for the current function?

**Comment by akhmerov** [comment]
Linking a related issue: #40
