### ISSUE TITLE
readthedocs gives attribute error

### ISSUE THREAD

**Issue by abhigyanprksh** [jupyter/jupyter-sphinx#128]
This is the build error I am getting while building my documents using Sphinx on readthedocs: https://readthedocs.org/projects/gunsnfloyd2k19/builds/11088427/

This is working fine locally. Are there any additional dependencies that need to be speicified?
My project link: https://github.com/abhigyanprksh/sphinx-jupyter

**Comment by akhmerov** [comment]
Thanks for reporting. This is a regression introduced in #107 (released as version 0.2.4). It has been reported in #126. I'm closing this issue as a duplicate, please track the other one.
