### ISSUE TITLE
Widgets are not rendering while building on readthedocs

### ISSUE THREAD

**Issue by abhigyanprksh** [jupyter/jupyter-sphinx#129]
I was trying to use the latest version of `jupyter-sphinx` while building documentation on readthedocs, but I was getting a build error. I changed the version to 0.2.3, now the build is successful, however, the widgets are not rendering. Everything is working fine locally though. Are there any additional dependencies that need to be provided for readthedocs?
Here are my project files: https://github.com/abhigyanprksh/sphinx-jupyter

**Comment by akhmerov** [comment]
Please try to provide a minimal example to what doesn't work, or at least point directly both to the source code and the output that doesn't render correctly. This repository does contain widget examples and it is deployed on rtd.

**Comment by abhigyanprksh** [comment]
https://github.com/abhigyanprksh/sphinx-jupyter/blob/master/docs/source/jup1.rst This part doesn't render correctly. There is no widget, however, the build was successful on rtd: https://gunsnfloyd2k19.readthedocs.io/en/latest/jup1.html

**Comment by akhmerov** [comment]
From the build logs:

```

/home/docs/checkouts/readthedocs.org/user_builds/gunsnfloyd2k19/checkouts/latest/docs/source/jup1.rst:4: WARNING: Unknown directive type "jupyter-execute".

.. jupyter-execute::
        :hide-output:

        name = 'world'
        print('hello ' + name + '!')
```

Furthermore, 

```
WARNING: extension 'jupyter_sphinx' has no setup() function; is it really a Sphinx extension module?
```

That's because in 0.2.3 one needed to specify `jupyter_sphinx.execute` as an extension. That still works in 0.2.4, but is deprecated.

**Comment by abhigyanprksh** [comment]
Thanks, works now!
