### ISSUE TITLE
cannot replicate jupyter_sphinx docs build

### ISSUE THREAD

**Issue by GavinHuttley** [jupyter/jupyter-sphinx#131]
First, awesome project -- am switching all my docs to using it -- so thank you!

The main issue is the line numbers are not showing up. I've done this using the attached conda environment file (
attached as [jsp_env.yml.zip](https://github.com/jupyter/jupyter-sphinx/files/4839818/jsp_env.yml.zip) for convenience, but displayed as literal below) that attempts to mirror your `requirements.txt`.

```
name: jsp
channels:
  - conda-forge
  - defaults
dependencies:
  - matplotlib
  - pip
  - python=3.8
  - pip:
    - sphinx==1.8.5
    - ipywidgets>=7.0.0
    - nbconvert>=5.4
    - nbformat
    - git+https://github.com/jupyter/jupyter-sphinx.git@master#jupyter_sphinx
```

With conda installed, created env as `$ conda env create -f jsp_env.yml`. Activate the environment (`$ conda activate jsp`) then create a jupyter kernel

```
$ python -m ipykernel install --sys-prefix --name python3 --display-name python3
```

Within the doc directory a downloaded copy of jupyter-sphinx master, ran `$ make html` which produced the attached [html.zip](https://github.com/jupyter/jupyter-sphinx/files/4839821/html.zip).

I'm running this on MacOS Catalina in the conda environment above.

**Comment by akhmerov** [comment]
@GavinHuttley I've made a new release recently, with a bunch of bugfixes. Does the problem still persist?

**Comment by GavinHuttley** [comment]
This was fixed in the latest release. Thanks!
