### ISSUE TITLE
nbextension install and enable

### ISSUE THREAD

**Issue by jrdzha** [jupyter/jupyter-sphinx#136]
I have a jupyter extension that requires calling:

```
jupyter nbextension install
jupyter nbextension enable
```

Is there a way to achieve this with jupyter-sphinx?

**Comment by akhmerov** [comment]
Notebook extensions are a part of the jupyter server; jupyter-sphinx doesn't run a notebook server at all.

What does your extension do? What are you trying to achieve?

NB: if your extension renders something on the frontend, I think you'll need to include the relevant javascript on your own (possibly via sphinx extension).

**Comment by akhmerov** [comment]
I'm going to close this issue, feel free to reopen/open a new one if something isn't addressed.
