### ISSUE TITLE
Custom CSS file gets overwritten

### ISSUE THREAD

**Issue by hagenw** [jupyter/jupyter-sphinx#149]
I tried to add a `custom.css` file as described in the documentation with:

```python
html_static_path = ['_static']
html_css_files = ['css/custom.css']
```

But the CSS files are imported in the wrong order in the resulting HTML header and `custom.css` gets overwritten by `jupyter-sphinx.css`:

```html
<head>

  <!--[...]-->

  <link rel="stylesheet" href="_static/css/theme.css" type="text/css" />
  <link rel="stylesheet" href="_static/pygments.css" type="text/css" />
  <link rel="stylesheet" href="_static/copybutton.css" type="text/css" />
  <link rel="stylesheet" href="_static/css/custom.css" type="text/css" />
  <link rel="stylesheet" href="_static/jupyter-sphinx.css" type="text/css" />

  <!--[...]-->

</head>

**Comment by hagenw** [comment]
This seems to be related to the fact that `jupyter-sphinx.css` is [injected during the builder init stage](https://github.com/jupyter/jupyter-sphinx/blob/v0.3.0a1/jupyter_sphinx/__init__.py#L91-L117).

If I include `custom.css` the following way in my `docs/conf.py` it works:

```python
html_static_path = ['_static']


def builder_inited(app):
    app.add_css_file("css/custom.css")


def setup(app):
    app.connect("builder-inited", builder_inited)
```

I would propose to document this behavior, or better changing the code that the normal inclusion of `custom.css` works.

**Comment by akhmerov** [comment]
Yes, I think we should fix the inclusion order instead.
