### ISSUE TITLE
Consider adding the sphinx-extension GitHub topic

### ISSUE THREAD

**Issue by jdillard** [jupyter/jupyter-sphinx#150]
Just wanted to say you should consider adding the sphinx-extension topic, https://github.com/topics/sphinx-extension, to the repo so it is easier for others to find on the GitHub ecosystem. There are currently 94 other sphinx extensions that use that topic.

**Comment by akhmerov** [comment]
@SylvainCorlay @choldgraf if you have some time to add the sphinx-extension github topic to this repo, it'd be great (I don't have sufficient permissions).

**Comment by choldgraf** [comment]
done 👍
