### ISSUE TITLE
Extensions in Javascript - ipympl

### ISSUE THREAD

**Issue by srush** [jupyter/jupyter-sphinx#164]
I would love to use https://github.com/matplotlib/ipympl in order to have interactive graphs in my pages. 

Everything compiles fine, but it can't find the extension javascript -> `jupyter-matplotlib.js` 

Is there something I need to do to make that work?

Thanks! Project is really neat.

**Comment by akhmerov** [comment]
I fear the problem here is more profound. Correct me if I'm wrong, but iirc `ipympl` relies on backend to render the plots. You can confirm it by killing the kernel and observing that the plot rendering breaks. Therefore even including javascript won't resolve your problem.

**Comment by srush** [comment]
Oh I didn't realize. Any options for rendering mildly interactive matplotlib on the frontend that work here?

**Comment by akhmerov** [comment]
I think you need bokeh, plotly instead. I think both have tools for ingesting mpl figures, or at least plotly does.

**Comment by akhmerov** [comment]
I'm going to close this issue, feel free to reopen/open a new one if something isn't addressed.

**Comment by srush** [comment]
I switched to plotly and it works amazing! Thanks so much for the package 

Demo: https://minitorch.github.io/mlprimer.html#parameters

**Comment by akhmerov** [comment]
Nice!
