### ISSUE TITLE
Using ipynb files as input?

### ISSUE THREAD

**Issue by niklassiemer** [jupyter/jupyter-sphinx#168]
Hi,
I just want to know if it is possible to provide ipynb files in the 
.. jupyter-execute:: example.ipynb
directiv? I am looking for a tool to dispay notebooks interactively inside a package documentation.
Thanks!

**Comment by chrisjsewell** [comment]
(https://github.com/executablebooks/MyST-NB, https://github.com/executablebooks/jupyter-book 👀)

**Comment by akhmerov** [comment]
@chrisjsewell is correct: parsing notebooks as input is beyond the scope of this project. For completeness, there's also https://github.com/spatialaudio/nbsphinx, although the jupyter-book stuff is much more feature-complete.

**Comment by niklassiemer** [comment]
Thanks a lot!
