### ISSUE TITLE
Issue with loading JS bundle from unpkg.com

### ISSUE THREAD

**Issue by sackh** [jupyter/jupyter-sphinx#174]
Hi,
I have a [jupyter widget](https://github.com/heremaps/here-map-widget-for-jupyter) and I am building docs using `jupyter-sphinx` 

Below are packages published on PyPI and NPM
https://pypi.org/project/here-map-widget-for-jupyter/
https://www.npmjs.com/package/@here/map-widget-for-jupyter

Docs: 
https://here-map-widget-for-jupyter.readthedocs.io/en/stable/

I have the bundle uploaded on unpkg.com here: 
https://unpkg.com/@here/map-widget-for-jupyter@0.1.1/dist/index.js

But in the console logs, I can see that in `embed-amd.js` it is looking for the bundle in this URL: 
https://unpkg.com/map-widget-for-jupyte0.1.1/dist/index.js 

I tried changing `publicPath` in `webpack.config.js` but it does not help.

can someone help me resolve this issue?

<img width="863" alt="Screenshot 2021-02-09 at 2 08 59 PM" src="https://user-images.githubusercontent.com/8600927/107338269-5cad9e00-6ae1-11eb-98b7-0dd5b8c17aa1.png">
<img width="865" alt="Screenshot 2021-02-09 at 2 09 38 PM" src="https://user-images.githubusercontent.com/8600927/107338281-5e776180-6ae1-11eb-817c-c0640621d724.png">

**Comment by akhmerov** [comment]
This one is a tough one to get, because finding the widget javascript is done by ipywidgets themselves; we're only using that machinery. @SylvainCorlay would you know how to approach this problem (or whom else to ask from the ipywidgets crowd)?

**Comment by sackh** [comment]
Sorry, it was my bad, I missed scope on the python side and hence ipywidgets was not able to identify it. Thanks to @martinRenou for helping in identifying the fix for this issue.
