### ISSUE TITLE
how to go interactive using local server ?

### ISSUE THREAD

**Issue by sebastien-riou** [jupyter/jupyter-sphinx#175]
On one side [the doc](https://jupyter-sphinx.readthedocs.io/en/latest/#thebelab-support) shows how to go interactive via Thebelab / binder
On another side Thebelab doc has [an example](https://thebelab.readthedocs.io/en/latest/_static/local.html) showing how to use a local server
I would like to combine both, but can't find how. The use case is for people working in offline environment.

**Comment by akhmerov** [comment]
Since jupyter-sphinx accepts generic thebelab config, it seems to me that you would achieve the desired result by providing an appropriate thebe config to jupyter-sphinx (see the page source of the example you linked for how this config would look like).

Does that answer your question, or am I missing some aspects?

**Comment by sebastien-riou** [comment]
@akhmerov 
Thanks for the hint, I did not realized that the documentation for `jupyter_sphinx_thebelab_config` would be simply the documentation for thebelab configuration. 

I am getting closer, the "make live" button does start a kernel however running a cell just display "Waiting for kernel..." forever.
Do you have another hint for me ?

Note that at this point I think the issue is not related to jupyter-sphinx at all, so you may very well close that issue and go on developing awesome stuff :-)

in conf.py:
````
jupyter_sphinx_thebelab_config = {
  'requestKernel': True,
  'kernelOptions': {
    'name': "python3",
    'serverSettings': {
      "baseUrl": "http://127.0.0.1:8888",
      "token": "test-secret"
    }
  },
}
````

server window:
````
user@lafite:~$ jupyter notebook --NotebookApp.token=test-secret --NotebookApp.allow_origin='http://localhost:8888'
[I 12:59:24.682 NotebookApp] Serving notebooks from local directory: /home/user
[I 12:59:24.682 NotebookApp] Jupyter Notebook 6.2.0 is running at:
[I 12:59:24.682 NotebookApp] http://localhost:8888/?token=...
[I 12:59:24.682 NotebookApp]  or http://127.0.0.1:8888/?token=...
[I 12:59:24.682 NotebookApp] Use Control-C to stop this server and shut down all kernels (twice to skip confirmation).
[I 12:59:46.985 NotebookApp] Kernel started: 8ec7273c-963b-494f-9ad2-55d2df52baeb, name: python3

````

**Comment by akhmerov** [comment]
It could be that 127.0.0.1 and localhost are not treated as the same origin (browsers certainly make this distinction).
Additionally you should check the browser dev console for errors.

**Comment by sebastien-riou** [comment]
thanks for the suggestion looking at the browser dev console did give a clue: the webpages (example or generated by sphinx) are sending 'null' as origine, so 'localhost' and '127.0.0.1' are both denied.
I solved it simply by changing the `allow_origin` in jupyter command line, not sure if that's safe but it is functional
`jupyter notebook --NotebookApp.token=test-secret --NotebookApp.allow_origin='null'`

**Comment by akhmerov** [comment]
Ah, I see; this is likely because you're opening those pages via `file://` protocol; if you instead serve the pages via e.g. `python -m http.server 8000`, it might work also with specifying origin.

It seems that the question is resolved, and therefore I'm going to close this issue. Please feel free to reopen if new problems arise.
