### ISSUE TITLE
Warning in sphinx 4.0.0

### ISSUE THREAD

**Issue by caenrigen** [jupyter/jupyter-sphinx#182]
Sphinx released a new version that seems to cause this kind of warnings:

```bash
WARNING: unknown directive or role name: jupyter-download:notebook
WARNING: unknown directive or role name: jupyter-download:script
```

when using something like:

```
:jupyter-download:notebook:`Tutorial 1`
:jupyter-download:script:`Tutorial 1`
```

The docs build seems to be ok with the correct output, might just make some pipelines fail due to the warnings

**Comment by spluque** [comment]
Is there a work around for this issue?
