### ISSUE TITLE
IPython question mark does not display output

### ISSUE THREAD

**Issue by moorepants** [jupyter/jupyter-sphinx#193]
I have lines like:

```rst
.. jupyter-execute::
   ?

.. jupyter-execute::
   function?
```

The output that displays in IPython or Jupyter notebook does not seem to display with jupyter-sphinx. For example:

![image](https://user-images.githubusercontent.com/276007/149672768-7ac0e41b-367d-4c46-b4a5-e3fd6ca03926.png)

Is there a way to have the output from the IPython `?` and `??` display?

**Comment by akhmerov** [comment]
You are observing https://github.com/jupyter/nbclient/issues/196. I don't think we can offer a workaround on the jupyter-sphinx side. Pinning nbclient or IPython versions would probably be unnecessarily disruptive, and therefore I propose to close this issue. Let me know if you disagree.

**Comment by moorepants** [comment]
Thanks. Yes, fine to close this in favor of the nbclient one. I believe that nbconvert does handle this correctly and puts the output of `?` into an output cell (maybe not relevant though).

**Comment by akhmerov** [comment]
nbconvert directly uses nbclient for execution, and therefore has the exact same problem (I also checked that).

**Comment by moorepants** [comment]
Interesting. Here is an example of it working with nbviewer:

https://nbviewer.org/github/moorepants/mae223/blob/master/content/lecture-notebooks/mae223-l02.ipynb

![image](https://user-images.githubusercontent.com/276007/149675626-f7f1e140-5d62-43ec-9315-deaaa502908b.png)

But I'm not sure what the difference is.

**Comment by akhmerov** [comment]
Can't confirm using `jupyter nbconvert --execute bug.ipynb --to notebook --stdout` (`bug.ipynb` contains a single code cell with `?`).

Your notebook already contains outputs; was it not executed manually, e.g. using run all cells or so?

**Comment by moorepants** [comment]
Yes, manually executed then uploaded to github and displayed via nbviewer. So I guess manual execution of the notebook catches the output properly. Thanks.
