### ISSUE TITLE
Could not import module name `astroid`

### ISSUE THREAD

**Issue by choldgraf** [jupyter/jupyter-sphinx#209]
In the pydata theme this extension kinda randomly started failing with an error about `astroid` not being present (I'm not sure what this is):

https://github.com/pydata/pydata-sphinx-theme/runs/7727153212?check_suite_focus=true#step:5:17

Any idea what could be causing this?

**Comment by akhmerov** [comment]
No idea; `astroid` seems to be an AST implementation, which is used by code quality tools. However looking at all jupyter-sphinx imports, I can't find anything that would drag it in. The CI logs are fairly minimal, are you able to reproduce this locally?

**Comment by choldgraf** [comment]
I re-built today and the problem went away...I think it might have been a transient issue with IPython, so will close this!
