### ISSUE TITLE
Specifying script path does not support more than one level above.

### ISSUE THREAD

**Issue by germa89** [jupyter/jupyter-sphinx#223]
This will work:

```rst

.. jupyter-execute:: ../myscript.py

```

Whereas this will fail:

```rst
.. jupyter-execute:: ../../myscript.py

```

(Of course the script in the second example is located one level above the previous one)

**Comment by 12rambau** [comment]
I tried on my machine, moving around a `script.py` file and it worked as expected consistently so I'll close this issue for now. Please reopen with more details if you still face it on your end.
