### ISSUE TITLE
Is this project still maintained ? 

### ISSUE THREAD

**Issue by 12rambau** [jupyter/jupyter-sphinx#234]
I see that the latest push to master was in June 2022 and some of the CI/Python versions are slowly starting to fail. PRs have been suggested to solve them but I don't know if the maintainers of the project still have time to dedicate to this repository. 

In the end, everything is in the title, and I of course offer help if I can be useful.

**Comment by Peque** [comment]
@akhmerov Have you recently discussed internally your position/vision with respect to `jupyter-sphinx`?

(Asking you since you were also involved when discussing https://github.com/jupyter/jupyter-sphinx/issues/36) :blush:

**Comment by 12rambau** [comment]
Thanks to the Jupyter team, for having me onboard, I'll try my best to answer some question and small the most pressing issues of the lib !
