### ISSUE TITLE
re-authorize merge commits to main branch

### ISSUE THREAD

**Issue by 12rambau** [jupyter/jupyter-sphinx#269]
@blink1073 could you change the rules applied to the main branch and re-authorize merge commits as discussed in https://github.com/jupyter/jupyter-sphinx/pull/237. I  wanted to start merging bigger PR and only squash merges are allowed on main.

As a maintainer, I can do it in global config but I don't have enough rights to change branch rules.

**Comment by blink1073** [comment]
<img width="408" alt="image" src="https://github.com/jupyter/jupyter-sphinx/assets/2096628/eaf15d06-acbe-48d0-9f3e-5a9a3c905c6e">

As I said, I think "Rebase and merge" is a much better option, it preserves the order of the history without having a merge commit.

**Comment by 12rambau** [comment]
I tried on #268 and it's creating a conflict that cannot be solved from the GH interface. As @akhmerov and I were ok to go back to the previous workflow I thought it was just a matter of applying it. I'm sorry if I look stubborn but I really don't see the advantage of forcing the use of either squash or rebase compared to merge considering the drawbacks I already mentioned and seeing now that it requires extra work to do something that is transparent with the default merge.

**Comment by blink1073** [comment]
I will disagree and move on, I changed the policy.

**Comment by 12rambau** [comment]
thanks a lot, I'm sure your method is better, we simply didn't face the need so we behave like spoiled child ;-)
