### ISSUE TITLE
Move to Jupyter GitHub organization?

### ISSUE THREAD

**Issue by SylvainCorlay** [jupyter/jupyter-sphinx#50]
Since jupyter-sphinx is not widgets-specific, it could make sense to move it to the more general Jupyter GitHub organization.

What do you think?

**Comment by akhmerov** [comment]
Yes, sounds great.

**Comment by akhmerov** [comment]
@SylvainCorlay because #53 will need to hard-code the path to this repository (we'll want to provide binder config), can you please execute the move?

**Comment by akhmerov** [comment]
TODO: update the binder path in thebelab settings.

**Comment by akhmerov** [comment]
Thanks @SylvainCorlay
