### ISSUE TITLE
doc: mention related packages

### ISSUE THREAD

**Issue by akhmerov** [jupyter/jupyter-sphinx#64]
At the very least, nbsphinx and sphinx gallery have each their own advantages, and we should mention these as well as any other reasonable packages that may be used to fulfill a similar role.

**Comment by 12rambau** [comment]
here is the list of the one I know: 
- juyterlite
- thebe
- myst-nb
- nbsphinx
- ipython

**Comment by Peque** [comment]
@12rambau Would it make sense to add Executable Books? (mentioned in https://github.com/jupyter/jupyter-sphinx/issues/36#issuecomment-1019308962).

**Comment by 12rambau** [comment]
to my understanding, [executablebooks](https://github.com/executablebooks) is a project and their execution sphinx extension is [myst-nb](https://github.com/executablebooks/MyST-NB) that I mentioned in the seealso section of the latest index.html 

Did I miss something ? (FYI I rarely use it)

**Comment by Peque** [comment]
@12rambau Understood. Thanks! :blush:
