### ISSUE TITLE
Allow disabling of stderr printing

### ISSUE THREAD

**Issue by jbweston** [jupyter/jupyter-sphinx#72]
Sometimes when importing certain packages there are various warnings that are raised. These warnings are often unavoidable and are not the fault of the end user.

Currently we raise an exception whenever anything is printed to `stderr`, however it seems that the correct way to handle these warning messages is just to suppress them entirely; i.e. not to print to `stderr` and also not to raise an exception.

I propose a configuration parameter that suppresses `stderr` and does not raise an exception when it is printed to.

**Comment by akhmerov** [comment]
Sounds reasonable; can you make a specific example?

**Comment by jbweston** [comment]
In the adaptive documentation scikit learn complains about joblib, and we cannot even suppress the warnings by the usual mechanisms (this is a known issue apparently)
