### ISSUE TITLE
Use same kernel for multiple documents

### ISSUE THREAD

**Issue by pohlt** [jupyter/jupyter-sphinx#74]
Thanks for this great extension.

I'm currently preparing a training script which consists of multiple RST files collected in a central index.rst like this:

    .. toctree::

        introduction
        data_io
        misc

It seems like each file (introduction, data_io, misc) uses a separate kernel (or maybe the kernel is being reset implicitly). How can I run all code snippets in one kernel and still have this separation of these lengthy documents?

Cheers,
Tom

**Comment by akhmerov** [comment]
Hi Tom, thanks for the suggestion! The idea sounds like a potentially useful feature.

At the same time I think this is rather complex to support both from the point of view of the interface (how should the creator of documentation indicate that multiple documents should share the kernel), as well as the implementation (we need to figure out where to intervene in the sphinx processing pipeline so that we already know which documents expect to share a kernel).

**Comment by pohlt** [comment]
Dear Anton,
thanks for taking the time to explain the hurdles to realize this idea. I didn't know that the files are processed this independently by sphinx. Now I fully understand why this would be difficult to achieve.

What I did now is to put the relevant code in a separate module and do a hidden important in subsequent documentation files.

Cheers,
Tom

**Comment by teibit** [comment]
A way in which the user could specify the kernel would be by simply specifying its ID.

Assume in file **a.rst** we declare

```
.. jupyter-kernel:: python3
    :id: working_kernel
```

Then it would definitely be intuitive to include in another file **b.rst**

```
.. jupyter-kernel:: python3
    :id: working_kernel
```

and expect the kernel `working_kernel` to be the same across both files.

**Comment by akhmerov** [comment]
@teibit but what would be the order in which the cells execute? Determined from TOC?

**Comment by akhmerov** [comment]
Also: wouldn't this be potentially confusing for the documentation authors when changes in one document result in changes in another document.

**Comment by teibit** [comment]
I totally agree this would be very confusing to think about –– let alone implement.

A simple strategy I've adopted is to have a code file with definitions intended to be shared across multiple files and simply include in each file

```
.. jupyter-execute:: <path/to/code.py>
    :hide-code:
```

so that different things can be done in each one.

**Comment by SeanDS** [comment]
This would be a great feature, and it would be great if it would also allow multiple kernels inside the _same_ documents. Some code snippets might change the kernel state enough that you don't want to run some other script in the same kernel. Having an `id` would also be great for being able to reset the line numbering inside new code snippets. For example, I would like to be able to do this:

```
One way to achieve [thing] is to write a script like this:

[jupyter-execute directive with kernel ID 1; shows lines 1-10]

You can plot it with the `plot` command:

[jupyter-execute directive with kernel ID 1, shows line 11]

Alternatively, a quicker way to do [thing] is this way:

[jupyter-execute directive with kernel ID 2, shows lines 1-5]
```

The idea would be that the first two blocks would number their lines from 1-10 in the first, 11 in the second, then go back to 1-5 in the third.

**Comment by akhmerov** [comment]
@SeanDS you can already start a new kernel within the same document, and iirc this resets the line numbering.

**Comment by SeanDS** [comment]
Ah I missed that the `:id:` attribute was already available. Great, thank you!

**Comment by jbweston** [comment]
It seems that the consensus is that this is a `wontfix` due to difficulties in defining consistent semantics.

It seems that several workarounds for prominent usecases were accepted, so I'm going to close this. Any objections and we can re-open later.
