### ISSUE TITLE
Configuring ThebeButton

### ISSUE THREAD

**Issue by oscarys** [jupyter/jupyter-sphinx#75]
Hi,

Wonderful extension. Many thanks to everyone involved !!

I looked into using the `.. thebe-button <displayed text>` directive, which already allows the user to modify the text displayed within the button. However, the text that pops out when hovering over the button is always "Make live". I know this is certainly a very minor thing, but wouldn't it be nice making this text also configurable? I wish I knew the details to help with some code.

**Comment by akhmerov** [comment]
Thanks for reporting, should be good now.

**Comment by oscarys** [comment]
Tested, it's working fine. Thanks.
