### ISSUE TITLE
Interactivity with / without ThebeLab

### ISSUE THREAD

**Issue by oscarys** [jupyter/jupyter-sphinx#76]
Hi !

I'm trying to add some interactivity to a page using `.. jupyter-execute::`, but unfortunately my approach is not working and I am not grasping the key issues involved. I provide a simple example that runs perfectly in Jupyter Lab, with an IntSlider input whose 'value' gets squared and displayed as a Label's 'value'. Everything happens in the callback registered using the `.observe` handler:

```python
import ipywidgets as widgets
val = 2
inp = widgets.IntSlider(value = val, min = 1, max = 10, 
                        description = 'x', readout = False)
out = widgets.Label(r'\({0}^2 = {1}\)'.format(val,val*val))
def handle_inp_change(value):
    out.value = r'\({0}^2 = {1}\)'.format(value.new,value.new*value.new)
inp.observe(handle_inp_change,'value')
display(widgets.HBox([inp,out]))
```
So this works fine both in a Jupyter Lab cell, and within my sphinx-rendered page when I activate ThebeLab and run the cell using the 'run' button (the code is properly formatted in markdown for `..jupyter-execute::`). But .... if I only load the page in the browser without activation of ThebeLab, it occurs that while the slider responds to mouse actions, nothing happens within the Label. If I'm understanding correctly, `..jupyter-execute::` creates a cell with nbconvert and runs it "somewhere", isn't it ?

Sorry for the lengthy description, but I am sure that this problem is a good instance of many other possible designs that need to be interactive. I'll be glad to explain again or provide more info, and certainly will be more than happy to read your feedback.

**Comment by akhmerov** [comment]
> If I'm understanding correctly, ..jupyter-execute:: creates a cell with nbconvert and runs it "somewhere", isn't it ?

The execution in jupyter-sphinx happens at the build time, so just like with nbviewer there is no live kernel unless you use thebelab.

Does that answer your question?

**Comment by oscarys** [comment]
Thanks @akhmerov , it does answer my question. However now I have a couple of comments, maybe rooted in big ignorance from my part. I hope not to sound or be a fool wasting your time.

1) If all the machinery is there for running code through ThebeLab, wouldn't it be nice if there was a way of firing up a live widget interface on a page as soon as it is rendered, so that the reader doesn't have to click buttons to "go live" and "run" (while having the code hidden with `:hide-code:` directives) ? (I've seen that behavior in [jupyter-book](https://jupyter.org/jupyter-book/intro.html))

2) Being that execution happens at build time, I guess the only way of gaining my desired interactivity is by building custom javascript widgets, is that right? Is that the way that HoloViews or Adaptive incorporate the interactive functionality that can be seen for example [in the adaptive documentation](https://adaptive.readthedocs.io/en/latest/tutorial/tutorial.LearnerND.html) ? 

Thanks again.

**Comment by akhmerov** [comment]
No problem at all.

1. The machinery for running thebelab is based on limited resources kindly provided by binder. One can in principle request a binder every time the user starts a new browsing session, but that would be rather resource-inefficient. I see that jupyter-book uses `nbinteract`, which also goes via binder though, and they should be equally aware about the resource usage. So this would indeed be possible, although I have mixed feelings about it.

2. Indeed holoviews and adaptive use static widgets to enable rich UI.

**Comment by oscarys** [comment]
Thanks @akhmerov for your reply. I agree that caring for good use of resources like binder is relevant. Probably a midpoint solution might be to have an option to enable binder for the browsing session by request... a button in the documentation home page, or next to the index ?

> Indeed holoviews and adaptive use static widgets to enable rich UI.

I'll go into learning about extending ipywidgets =)

All the best !

**Comment by jbweston** [comment]
@oscarys it seems like your question was answered so I'm going to close this issue.

If I have misunderstood feel free to re-open.
