### ISSUE TITLE
sphinx.ext.mathbase is deprecated

### ISSUE THREAD

**Issue by mgeier** [jupyter/jupyter-sphinx#77]
You are using this:

https://github.com/jupyter/jupyter-sphinx/blob/6eb778a741c65b562ef0750551b8dbe50a4eff49/jupyter_sphinx/execute.py#L14

Which is deprecated since Sphinx version 1.8, see:

https://www.sphinx-doc.org/en/master/extdev/deprecated.html

https://www.sphinx-doc.org/en/master/usage/extensions/math.html

**Comment by akhmerov** [comment]
Thanks for reporting!

**Comment by akhmerov** [comment]
closed via #78
