### ISSUE TITLE
Add Github repo link to docs

### ISSUE THREAD

**Issue by seanpue** [jupyter/jupyter-sphinx#79]
Let me first say, I love this project!

One issue: there is no link back to the Github repo in the docs, which is annoying.  I can add one if you like, e.g. "the fork me on github" widget which works well with alabaster.

**Comment by akhmerov** [comment]
Thanks!

Good idea, and your contribution would be very welcom! I personally prefer how it's implemented in e.g. https://thebelab.readthedocs.io/en/latest/ to "fork me on github" banner, but either way is fine.
