### ISSUE TITLE
config option to truncate traceback

### ISSUE THREAD

**Issue by seanpue** [jupyter/jupyter-sphinx#84]
It would be useful to be able to be able to have the option to truncate the display of error traceback. When writing documentation, it is useful just to show that an error occurred without showing the full traceback. This practice is commonly done in terminal view.

There is ``sys.tracebacklimit`` setting. However, it does not work in Jupyter and needs a rather complex override: https://stackoverflow.com/questions/46222753/how-do-i-suppress-tracebacks-in-jupyter

I would propose adding a ``jupyter_sphinx_truncate_traceback`` option that would just show the first two lines of the normal traceback message followed by an ellipsis, e.g.
```
---------------------------------------------------------------------------
ZeroDivisionError                         Traceback (most recent call last)
...
```

**Comment by akhmerov** [comment]
Thanks for the proposal!

I however think this is too specific: the rendering of the tracebacks is already a very narrow scope application in writing package documentation.

The proposed implementation also uses specific information about how the IPython kernel renders traceback, rather than relying exclusively on the notebook format spec, making the feature very much Python-specific.

**Comment by seanpue** [comment]
For truncating traceback, one language-agnostic alternative would be to focus on # of lines (`traceback_line_limit`) and then change the parameter to an `int`. That will work across languages when applied to the joined traceback field output. (The default `language` for traceback is `ipythontb`, so that might be another field to make configurable.) Limiting or formatting traceback output is not a narrow or unusual task.

Another alternative would be to have customizable functions for the node generation of a subset (or all) of the different output types, including `stream`  (especially `stderr`) and `error`. These could return the element(s) to add to doctree nodes. Having some flexibility in those areas, in particular, would be useful and allow for language- or output-specific customization. 
That would entail passing the global configuration to `cell_output_to_node()`, calling the customizable functions, and providing their output to `to_add`. The display issues for `stderr` etc in #71 would probably need to be customizable based on the Sphinx theme and likely language, so that could be a good option.

**Comment by danielballan** [comment]
Would running `%xmode Minimal`, perhaps in a hidden cell, address this use case for Python-based kernels?

**Comment by akhmerov** [comment]
Sounds like a great suggestion. With hidden inputs it seems that kernel-side is the correct place to manage the outputs.

**Comment by seanpue** [comment]
Thanks @danielballan! That's a great solution, and it works in this use case.
