### ISSUE TITLE
add option to download code as notebook

### ISSUE THREAD

**Issue by seanpue** [jupyter/jupyter-sphinx#88]
Downloading the code as .py is great, but, if I am not reading things correctly (which is likely), there is no option to download the code on a particular webpage as  a notebook. That would be a good feature.

**Comment by jbweston** [comment]
We actually already have this: https://jupyter-sphinx.readthedocs.io/en/latest/#downloading-the-code-as-a-script

```
:jupyter-download:notebook:`index`
```

but maybe it's too lost in the documentation because it's not called out using an explicit example

**Comment by seanpue** [comment]
Ok, thanks!
