### ISSUE TITLE
Dollar signs when displaying sympy objects

### ISSUE THREAD

**Issue by jbweston** [jupyter/jupyter-sphinx#90]
Check the following examples:

https://qsymm.readthedocs.io/en/stable-1.2/tutorial/basics.html

![2019-11-11-150618_851x262_scrot](https://user-images.githubusercontent.com/6654709/68596513-a69d7380-049b-11ea-859a-fc2158cedf74.png)

The dollar signs do not appear when viewing the notebook version of the documentation

**Comment by akhmerov** [comment]
I see: this is consistent with jupyterlab's behavior—it is the responsibility of the contents of the latex object to include the delimiters for the math environment.

![image](https://user-images.githubusercontent.com/2069677/68713716-c2d60900-059e-11ea-9149-377edc554f83.png)

This is tricky though: we're wrapping the latex output within sphinx's `math_block`. Not sure what we can do as an alternative.

**Comment by akhmerov** [comment]
I have observed that sphinx math directive processes `\begin{<math_environment>}...\end{<math_environment>`. Therefore as a workaround I propose a regex-based replacement of `\(...\)`, `\[...\]`, `$...$`, and `$$...$$`.
